### ISSUE TITLE
Soru Listesi ekran tasarımının yapılması

### ISSUE THREAD

**Issue by yakintech** [yakintech/CatchMeMobile#1]

**Comment by bahadir-sengun** [comment]
Task tamamlandı. 
![Ekran Resmi 2024-09-03 15 59 08](https://github.com/user-attachments/assets/75d1504b-b347-4c0d-8eb0-a602326fb726)
![Ekran Resmi 2024-09-03 16 00 19](https://github.com/user-attachments/assets/eac7577e-bcd2-4f3a-a293-9c684efe4eb8)
