### ISSUE TITLE
Back butonunun kaldırılması

### ISSUE THREAD

**Issue by yakintech** [yakintech/CatchMeMobile#2]
<img width="360" alt="image" src="https://github.com/user-attachments/assets/6f57a7ad-46e9-434a-818d-bf5b50bf4e91">

**Comment by bahadir-sengun** [comment]
Tamamlandı.
![Ekran Resmi 2024-09-03 15 59 08](https://github.com/user-attachments/assets/d5ca962f-5545-4911-b25a-878eb6465a19)
